// product prices, inventory and dimensions are placeholder values based on latest pulled branch for local testing
// do we want to set style in here? suggesting this bc it the code will become lengthy in the seed.js file if we plan on using sequelize magic methods to set type on individual products

// products as object { room: [array of Products],
// set room using magic method
const products = {
  bedroom: [
    {
      name: 'Hartley King Bed',
      inventory: 10,
      height: 40,
      width: 83,
      depth: 89,
      material: 'fabric',
      color: 'grey',
      imagerUrl:
        'https://rnb.scene7.com/is/image/roomandboard/?src=ir%7Broomandboardrender/hartley_queen_60_2018?obj=main&sharp=1&src=rpt_declanhaze&obj=material&show&src=drape_material_cc&obj=hboard/40H&show&src=rpt_declanhaze%7D&$prodzoom0$&size=1280,400&scl=1',
      price: 2250.0,
      style: 'contemporary',
      type: 'bed',
    },
    {
      name: 'Miro King Bed',
      inventory: 10,
      height: 36.6,
      width: 71,
      depth: 92.1,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://images.hermanmiller.group/m/3effef93d8420f64/W-DWR_2517925_100169751_surf_oak_a.tif?blend-mode=darken&blend=f8f8f8&trim-color=ffffff&trim=color&bg=f8f8f8&auto=format&w=1200&q=68&h=1000',
      price: 1500.0,
      style: 'contemporary',
      type: 'bed',
    },
    {
      name: 'Niguel Dresser',
      inventory: 10,
      height: 33,
      width: 60,
      depth: 18,
      material: 'wood',
      color: 'beige',
      imagerUrl:
        'https://cdn.shopify.com/s/files/1/0351/7510/4651/products/2021_02_23_LAWSON_FENNING_0179_600x.png?v=1616896702',
      price: 875.0,
      style: 'contemporary',
      type: 'dresser',
    },
    {
      name: 'Kenwood Dresser',
      inventory: 10,
      height: 33,
      width: 84,
      depth: 20,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://rnb.scene7.com/is/image/roomandboard/?layer=0&size=1280,400&scl=1&src=899535_wood_SHELL&layer=1&size=1280,400&scl=1&src=899535_base_GP&layer=2&size=1280,400&scl=1&src=899535_pull_GRPH&layer=comp&$prodzoom0$',
      price: 1000.0,
      style: 'contemporary',
      type: 'dresser',
    },
    {
      name: 'Niguel Nightstand',
      inventory: 10,
      height: 24,
      width: 24,
      depth: 18,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://cdn.shopify.com/s/files/1/0351/7510/4651/products/2020_06_24_LAWSON_FENNING_0270-3_1200x.png?v=1596131972',
      price: 500.0,
      style: 'contemporary',
      type: 'nightstand',
    },
    {
      name: 'Copenhagen Nightstand',
      inventory: 10,
      height: 25,
      width: 26,
      depth: 20,
      material: 'wood',
      color: 'taupe',
      imagerUrl:
        'https://www.roomandboard.com/catalog/bedroom/nightstands/copenhagen-nightstands',
      price: 450.0,
      style: 'contemporary',
      type: 'nightstand',
    },
    {
      name: 'Nelson Thin Edge King Bed',
      inventory: 10,
      height: 35,
      width: 75,
      depth: 87,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://s7d2.scene7.com/is/image/HermanMillerStore/b2c_3x4crop?$image_src=HermanMillerStore/NelsonThinEdgeBed_10001010_Front&$b2c_1200x900_jpeg$',
      price: 2000.0,
      style: 'modern',
      type: 'bed',
    },
    {
      name: 'Lenia King Bed',
      inventory: 10,
      height: 45,
      width: 79,
      depth: 83,
      material: 'wood',
      color: 'black',
      imagerUrl:
        'https://cdn-images.article.com/products/SKU14680/2890x1500/image64105.jpg?fit=max&w=1920&q=80&fm=webp',
      price: 999.0,
      style: 'modern',
      type: 'bed',
    },
    {
      name: 'Nelson Thin Edge Dresser',
      inventory: 10,
      height: 28.5,
      width: 34,
      depth: 18.5,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://images.hermanmiller.group/m/3472754da72a027/W-HM_3654_10001994_walnut_aluminum_f.tif?blend-mode=darken&blend=f8f8f8&trim-color=ffffff&trim=color&bg=f8f8f8&auto=format&w=1200&q=68&h=1000',
      price: 600.0,
      style: 'modern',
      type: 'dresser',
    },
    {
      name: 'Lenia Dresser',
      inventory: 10,
      height: 32.5,
      width: 63,
      depth: 19,
      material: 'wood',
      color: 'beige',
      imagerUrl:
        'https://cdn-images.article.com/products/SKU14674/2890x1500/image62415.jpg?fit=max&w=1920&q=80&fm=webp',
      price: 1100.0,
      style: 'modern',
      type: 'dresser',
    },
    {
      name: 'Nelson Thin Edge Nightstand',
      inventory: 10,
      height: 23.75,
      width: 18,
      depth: 18.5,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://images.hermanmiller.group/m/3cf5eb614ce13485/W-HM_4358_9129742_ash_f.tif?blend-mode=darken&blend=f8f8f8&trim-color=ffffff&trim=color&bg=f8f8f8&auto=format&w=1200&q=68&h=1000',
      price: 850.0,
      style: 'modern',
      type: 'nightstand',
    },
    {
      name: 'Lenia Nightstand',
      inventory: 10,
      height: 24,
      width: 20,
      depth: 15,
      material: 'wood',
      color: 'beige',
      imagerUrl:
        'https://cdn-images.article.com/products/SKU14676/2890x1500/image59616.jpg?fit=max&w=1920&q=80&fm=webp',
      price: 350.0,
      style: 'modern',
      type: 'nightstand',
    },
    {
      name: 'Cooper Wing Bed',
      inventory: 1,
      height: 54,
      width: 88,
      depth: 87.5,
      material: 'fabric',
      color: 'beige',
      imagerUrl:
        'https://bernhardt.com/sites/default/files/product/bernhardt_interiors_cooper_wing_bed_754h66-754fr66_front_1.jpg',
      price: 2125.0,
      style: 'transitional',
      type: 'bed',
    },
    {
      name: 'Jordan Button-Tufted Wing Bed',
      inventory: 10,
      height: 64,
      width: 88,
      depth: 87.5,
      material: 'fabric',
      color: 'gray',
      imagerUrl:
        'https://bernhardt.com/sites/default/files/product/bernhardt_interiors_jordan_bed_64in_front.jpg',
      price: 2550.0,
      style: 'transitional',
      type: 'bed',
    },
    {
      name: 'Auberge Dresser',
      inventory: 10,
      height: 39,
      width: 68,
      depth: 19,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://bernhardt.com/sites/default/files/product/351-044A.jpg',
      price: 1800.0,
      style: 'transitional',
      type: 'dresser',
    },
    {
      name: 'Domaine Blanc Dresser',
      inventory: 10,
      height: 38,
      width: 68.25,
      depth: 19.25,
      material: 'wood',
      color: 'cream',
      imagerUrl:
        'https://bernhardt.com/sites/default/files/product/374-052.jpg',
      price: 1600.0,
      style: 'transitional',
      type: 'dresser',
    },
    {
      name: 'Allure Nightstand',
      inventory: 10,
      height: 29.75,
      width: 35.25,
      depth: 21.25,
      material: 'wood',
      color: 'cream',
      imagerUrl:
        'https://bernhardt.com/sites/default/files/product/bernhardt_allure_nightstand_399-229_front.jpg',
      price: 665.0,
      style: 'transitional',
      type: 'nightstand',
    },
    {
      name: 'Linea Bachelor Nightstand',
      inventory: 10,
      height: 32,
      width: 38,
      depth: 19,
      material: 'wood',
      color: 'brown',
      imagerUrl:
        'https://bernhardt.com/sites/default/files/product/bernhardt_linea_bachelors_chest_384-230b.jpg',
      price: 525.0,
      style: 'transitional',
      type: 'nightstand',
    },
  ],
  living: [],
  dining: [],
  bathroom: [],
};

module.exports = { products };
